version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: foro-hub-auth-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - foro-hub-network
    healthcheck: # <-- AÑADIDO: Comprobación de salud del servicio
      test: ["CMD", "mysql", "--user=root", "--password=${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  auth-service:
    build:
      context: ./foro-hub-auth-service
      dockerfile: Dockerfile
    container_name: foro-hub-auth-service
    ports:
      - "8081:8081"
    networks:
      - foro-hub-network
    depends_on:
      db:
        condition: service_healthy # <-- MODIFICADO: Espera a que la BD esté saludable
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_FLYWAY_ENABLED: true
      MICROSERVICE_NOTIFICATION_URL: http://notifications-service:8080
      SERVICE_TO_SERVICE_SECRET: ${SERVICE_TO_SERVICE_SECRET}

  notifications-service:
    build:
      context: ./foro-hub-notifications-service
      dockerfile: Dockerfile
    container_name: foro-hub-notifications-service
    ports:
      - "8080:8080"
    networks:
      - foro-hub-network
    environment:
      SERVICE_TO_SERVICE_SECRET: ${SERVICE_TO_SERVICE_SECRET}
      INFOALURAFORO_PASSWORD: ${INFOALURAFORO_PASSWORD}

volumes:
  db_data:

networks:
  foro-hub-network:
    driver: bridge