INSERT INTO cursos (nombre, categoria) VALUES
('ChatGPT y programación: aumenta tu productividad', 'Programación'),
('ChatGPT: optimizando la calidad de los resultados', 'Programación'),
('Java: aplicando la Orientación a Objetos', 'Programación'),
('Java: consumir API, escribir archivos y manejar errores', 'Programación'),
('Java: creando tu primera API y conectándola al Front End', 'Programación'),
('Java: creando tu primera aplicación', 'Programación'),
('Java: persistencia de datos y consultas con Spring Data JPA', 'Programación'),
('Java: trabajando con lambdas, streams y Spring Framework', 'Programación'),
('Java: trabajar con listas y colecciones de datos', 'Programación'),
('Lógica de programación: explorar funciones y listas', 'Programación'),
('Lógica de programación: sumérgete en la programación con JavaScript', 'Programación'),
('Practicando con Java: Challenge Conversor de Monedas', 'Programación'),
('Practicando Java: condicionales con if/else', 'Programación'),
('Practicando Lógica de Programación: Challenge Amigo secreto', 'Programación'),
('Practicando Spring Boot: Challenge Literatura', 'Programación'),
('Spring AI: Integra una aplicación con OpenAI', 'Programación'),
('Spring Boot 3: aplique las mejores prácticas y proteja una API Rest', 'Programación'),
('Spring Boot 3: desarrolla una API REST en Java', 'Programación'),
('Spring Boot 3: documentar, probar y preparar una API para su implementación', 'Programación'),
('HTML y CSS: ambientes de desarrollo, estructura de archivos y tags', 'Front End'),
('HTML y CSS: Clases, Posicionamiento y Flexbox', 'Front End'),
('HTML y CSS: header, footer y variables CSS', 'Front End'),
('HTML y CSS: trabajando con responsabilidad y publicación de proyectos', 'Front End'),
('Aprender a aprender: técnicas para tu autodesarrollo', 'Innovación y Gestión'),
('Desarrollo de carrera: demanda del mercado', 'Innovación y Gestión'),
('Emprendimiento: De la idea al plan de negocios', 'Innovación y Gestión'),
('Foco: Enfocarse trae más resultados para el día a día', 'Innovación y Gestión'),
('Fundamentos de Agilidad: Primeros pasos para la transformación ágil', 'Innovación y Gestión'),
('Hábitos: Ser productivo para cumplir sus metas personales', 'Innovación y Gestión'),
('LinkedIn: Como hacer que tu perfil trabaje por ti', 'Innovación y Gestión'),
('Propósito profesional: ser el protagonista de tu carrera', 'Innovación y Gestión'),
('Transición de carrera: una guía al campo de tecnología', 'Innovación y Gestión'),
('Git y GitHub: repositorio, commit y versiones', 'DevOps');

